import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("sales_data.csv")
print("Dataset:")
print(df)
print("\nStatistical Summary:")
print(df.describe())
print("\nCorrelation Matrix:")
print(df[["Sales", "Profit"]].corr())
plt.figure(figsize=(8, 5))
plt.plot(df["Month"], df["Sales"], marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()
plt.figure(figsize=(8, 5))
plt.bar(df["Month"], df["Profit"])
plt.title("Monthly Profit")
plt.xlabel("Month")
plt.ylabel("Profit")
plt.show()
print("\nHighest Sales Month:")
print(df.loc[df["Sales"].idxmax()])
print("\nHighest Profit Month:")
print(df.loc[df["Profit"].idxmax()])
